# Generated by Django 4.2.2 on 2023-07-11 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, db_index=True, max_length=80, null=True, verbose_name='Nome Completo')),
                ('cpf', models.CharField(blank=True, db_index=True, max_length=14, null=True, verbose_name='CPF')),
                ('cpf_hashed', models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='CPF Hash')),
                ('rg', models.CharField(blank=True, max_length=9, null=True, verbose_name='RG')),
                ('gender', models.CharField(blank=True, max_length=20, null=True, verbose_name='Gênero')),
                ('ethnicity', models.CharField(blank=True, max_length=20, null=True, verbose_name='Etnia')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Data Nascimento')),
                ('photo', models.FileField(blank=True, null=True, upload_to='', verbose_name='Foto de Perfil')),
                ('state', models.CharField(choices=[('SP', 'São Paulo'), ('RJ', 'Rio de Janeiro'), ('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=200, verbose_name='Estado')),
                ('city', models.CharField(max_length=200, verbose_name='Cidade')),
                ('is_disabled', models.BooleanField(db_index=True, default=False, verbose_name='Possui deficiência')),
                ('disabled', models.CharField(blank=True, max_length=30, null=True, verbose_name='Deficiência')),
                ('is_internal', models.BooleanField(default=False)),
                ('is_company', models.BooleanField(default=False)),
                ('is_applicant', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
                'indexes': [models.Index(fields=['full_name'], name='users_profi_full_na_0369d9_idx'), models.Index(fields=['cpf', 'cpf_hashed'], name='users_profi_cpf_d960af_idx'), models.Index(fields=['is_disabled'], name='users_profi_is_disa_b4b2a7_idx')],
            },
        ),
    ]
