# Generated by Django 4.2.2 on 2023-07-18 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educational_institution', models.CharField(blank=True, max_length=80, null=True, verbose_name='Instituição de ensino')),
                ('course', models.CharField(blank=True, db_index=True, max_length=80, null=True, verbose_name='Curso')),
                ('knowledge_area', models.CharField(blank=True, max_length=80, null=True, verbose_name='Área do conhecimento')),
                ('started_at', models.DateTimeField(verbose_name='Iniciado em')),
                ('ended_at', models.DateTimeField(verbose_name='Finalizado em')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_formation', to='users.profile', verbose_name='Formação Acadêmica')),
            ],
            options={
                'verbose_name': 'Formação Acadêmica',
                'verbose_name_plural': 'Formações acadêmicas',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, db_index=True, max_length=80, null=True, verbose_name='Cargo')),
                ('job_type', models.CharField(choices=[('autonomo', 'Autônomo'), ('clt', 'CLT'), ('freelance', 'Freelance'), ('estagio', 'Estágio'), ('aprendiz', 'Aprendiz'), ('trainee', 'Trainee')], max_length=50, verbose_name='Tipo de trabalho')),
                ('job_modality', models.CharField(choices=[('presencial', 'Presencial'), ('hibrido', 'Híbrido'), ('home_office', 'Home Office')], max_length=50, verbose_name='Modalidade de trabalho')),
                ('is_working', models.BooleanField(default=False, verbose_name='Trabalhando atualmente')),
                ('company', models.CharField(blank=True, max_length=80, null=True, verbose_name='Empresa')),
                ('business_area', models.CharField(blank=True, max_length=80, null=True, verbose_name='Área de atuação da empresa')),
                ('started_at', models.DateTimeField(verbose_name='Iniciado em')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Finalizado em')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experience', to='users.profile', verbose_name='Experiência')),
            ],
            options={
                'verbose_name': 'Experiência',
                'verbose_name_plural': 'Experiências',
            },
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competence_name', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Competência')),
                ('academic_formation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.academicformation', verbose_name='Formação Acadêmica')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.experience', verbose_name='Experiência')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competence', to='users.profile', verbose_name='Competência')),
            ],
            options={
                'verbose_name': 'Competência',
                'verbose_name_plural': 'Competências',
            },
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['position'], name='users_exper_positio_7c3f93_idx'),
        ),
        migrations.AddIndex(
            model_name='competence',
            index=models.Index(fields=['competence_name'], name='users_compe_compete_cf28c1_idx'),
        ),
        migrations.AddIndex(
            model_name='academicformation',
            index=models.Index(fields=['course'], name='users_acade_course_383898_idx'),
        ),
    ]
