# Generated by Django 4.2.2 on 2023-07-18 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicformation',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_formation', to='users.profile', verbose_name='Formação Acadêmica'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competence', to='users.profile', verbose_name='Competência'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='users.profile', verbose_name='Perfil'),
        ),
    ]
