# Generated by Django 3.2.13 on 2023-07-19 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_academicformation_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicformation',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_formation', to='users.profile', verbose_name='Perfil'),
        ),
    ]
