# Generated by Django 3.2.13 on 2023-07-25 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_academicformation_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='academic_formation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.academicformation', verbose_name='Formação Acadêmica'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='experience',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.experience', verbose_name='Experiência'),
        ),
    ]
