# Generated by Django 3.2.13 on 2023-07-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20230725_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competence',
            name='academic_formation',
        ),
        migrations.AddField(
            model_name='competence',
            name='academic_formation',
            field=models.ManyToManyField(null=True, to='users.AcademicFormation', verbose_name='Formação Acadêmica'),
        ),
    ]
