# Generated by Django 3.2.13 on 2023-08-07 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('users', '0012_profile_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to='company.company', verbose_name='Empresa'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
