# Generated by Django 3.2.13 on 2023-08-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20230807_1230'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='profile',
            name='users_profi_full_na_0369d9_idx',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='full_name',
            new_name='name',
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['name'], name='users_profi_name_017717_idx'),
        ),
    ]
