# Generated by Django 3.2.13 on 2023-09-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20230905_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicformation',
            name='ended_at',
            field=models.DateTimeField(verbose_name='Finalizado em'),
        ),
        migrations.AlterField(
            model_name='academicformation',
            name='started_at',
            field=models.DateTimeField(verbose_name='Iniciado em'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finalizado em'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='started_at',
            field=models.DateTimeField(verbose_name='Iniciado em'),
        ),
    ]
