# Generated by Django 3.2.13 on 2023-09-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20230905_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='curriculum',
            field=models.FileField(blank=True, null=True, upload_to='curriculos', verbose_name='Currículo'),
        ),
    ]
