# Generated by Django 3.2.13 on 2023-10-01 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_auto_20230929_1404'),
        ('users', '0018_profile_curriculum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=250, verbose_name='Mensagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_profile', to='users.profile', verbose_name='Perfil')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_vacancy', to='company.vacancy', verbose_name='Vaga')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
            },
        ),
    ]
