# Generated by Django 3.2.13 on 2023-10-01 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_auto_20230929_1404'),
        ('users', '0019_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.profile', verbose_name='Perfil'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='company.vacancy', verbose_name='Vaga'),
        ),
    ]
