from .experience import JOB_TYPE, JOB_MODALITY
from .profile import STATES, GENDER_CHOICES, DISABLED_CHOICES, ETHNICITY_CHOICES
from .company import BUSINESS_AREAS_CHOICES
from .vacancy import SENIORITY_CHOICES, STATUS_VACANCY_CHOICES, VULNERABILITIES_CHOICES