BUSINESS_AREAS_CHOICES = [
    ('hotel', 'Hotelaria'),
    ('adm_sup_services', 'Serviços administrativos e suporte'),
    ('construction', 'Construção'),
    ('consumer_services', 'Atendimento ao consumidor'),
    ('education', 'Educação'),
    ('entertainment', 'Entreterimento'),
    ('farm_services', 'Agricultura, pecuária, silvicultura'),
    ('financial_services', 'Serviços financeiros'),
    ('holding_companies', 'Seguradoras'),
    ('hospitals_health_care', 'Hospitais e atendimento à saúde'),
    ('Manufacturing', 'Manufatura'),
    ('oil_gas_mining', 'Petróleo, gás e mineração'),
    ('professional_services', 'Serviços profissionais'),
    ('rental_services', 'Serviços de alguel'),
    ('retail', 'Varejo'),
    ('tech_info_media', 'Tecnologia, informação e internet'),
    ('trans_log_sup_stor', 'Transporte, logística, cadeia de suprimentos e armazenamento'),
    ('utilities', 'Serviços de eletricidade, gás, água e esgoto'),
    ('wholesale', 'Atacado'),
]