# Generated by Django 3.2.13 on 2023-08-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='business_areas',
        ),
        migrations.AddField(
            model_name='company',
            name='business_area',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Areas de atuação'),
        ),
    ]
