# Generated by Django 3.2.13 on 2023-08-31 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_alter_step_step_vulnerability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='step_vulnerability',
            field=models.CharField(choices=[('todos', 'Todos'), ('homens', 'Homens'), ('mulheres', 'Mulheres'), ('neutro', 'Gênero neutro'), ('nao_binario', 'Gênero Não binário'), ('transgenero', 'Gênero Transgênero'), ('auditiva', 'Pessoas com deficiência auditiva'), ('visual', 'Pessoas com deficiência visual'), ('motora', 'Pessoas com deficiência motora'), ('mental', 'Pessoas com deficiência mental'), ('branco', 'Branco'), ('preto', 'Preto'), ('amarelo', 'Amarelo'), ('indigena', 'Indígena'), ('pardo', 'Pardo')], default='todos', max_length=80, verbose_name='Para quem é a etapa'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='vulnerability',
            field=models.CharField(blank=True, choices=[('todos', 'Todos'), ('homens', 'Homens'), ('mulheres', 'Mulheres'), ('neutro', 'Gênero neutro'), ('nao_binario', 'Gênero Não binário'), ('transgenero', 'Gênero Transgênero'), ('auditiva', 'Pessoas com deficiência auditiva'), ('visual', 'Pessoas com deficiência visual'), ('motora', 'Pessoas com deficiência motora'), ('mental', 'Pessoas com deficiência mental'), ('branco', 'Branco'), ('preto', 'Preto'), ('amarelo', 'Amarelo'), ('indigena', 'Indígena'), ('pardo', 'Pardo')], max_length=50, null=True, verbose_name='Vulnerabilidade'),
        ),
    ]
