# Generated by Django 3.2.13 on 2023-08-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20230831_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='status',
            field=models.CharField(blank=True, choices=[('ATV', 'Ativo'), ('PEN', 'Pendente'), ('ENC', 'Encerrado')], default='PEN', max_length=10, null=True, verbose_name='Status'),
        ),
    ]
