# Generated by Django 3.2.13 on 2023-09-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_profile_curriculum'),
        ('company', '0009_alter_vacancy_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='status',
            field=models.CharField(blank=True, choices=[('PEN', 'Pendente'), ('ENC', 'Encerrado')], default='PEN', max_length=10, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='approved_candidates',
            field=models.ManyToManyField(related_name='vacancies_approved', to='users.Profile', verbose_name='Candidatos aprovados'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='candidates',
            field=models.ManyToManyField(related_name='vacancies', to='users.Profile', verbose_name='Candidatos'),
        ),
    ]
