# Generated by Django 3.2.13 on 2023-09-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_profile_curriculum'),
        ('company', '0010_auto_20230919_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='approved_candidates',
            field=models.ManyToManyField(blank=True, null=True, related_name='vacancies_approved', to='users.Profile', verbose_name='Candidatos aprovados'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='candidates',
            field=models.ManyToManyField(blank=True, null=True, related_name='vacancies', to='users.Profile', verbose_name='Candidatos'),
        ),
    ]
