# Generated by Django 3.2.13 on 2023-09-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_auto_20230925_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='about_us',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Sobre nós'),
        ),
        migrations.AlterField(
            model_name='step',
            name='step_vulnerability',
            field=models.CharField(choices=[('todos', 'Todos'), ('homens', 'Homens'), ('mulheres', 'Mulheres'), ('lgbt', 'LGBTQIAP+'), ('auditiva', 'Pessoas com deficiência auditiva'), ('visual', 'Pessoas com deficiência visual'), ('fisica', 'Pessoas com deficiência física'), ('intelectual', 'Pessoas com deficiência intelectual'), ('branco', 'Branco'), ('preto', 'Preto'), ('amarelo', 'Amarelo'), ('indigena', 'Indígena'), ('pardo', 'Pardo')], default='todos', max_length=80, verbose_name='Para quem é a etapa'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='vulnerability',
            field=models.CharField(blank=True, choices=[('todos', 'Todos'), ('homens', 'Homens'), ('mulheres', 'Mulheres'), ('lgbt', 'LGBTQIAP+'), ('auditiva', 'Pessoas com deficiência auditiva'), ('visual', 'Pessoas com deficiência visual'), ('fisica', 'Pessoas com deficiência física'), ('intelectual', 'Pessoas com deficiência intelectual'), ('branco', 'Branco'), ('preto', 'Preto'), ('amarelo', 'Amarelo'), ('indigena', 'Indígena'), ('pardo', 'Pardo')], max_length=50, null=True, verbose_name='Vulnerabilidade'),
        ),
    ]
