# Generated by Django 3.2.13 on 2023-09-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_auto_20230929_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='seniority',
            field=models.CharField(choices=[('jovem_aprediz', 'Jovem Aprendiz'), ('estagiario', 'Estagiário'), ('junior', 'Júnior'), ('pleno', 'Pleno'), ('senior', 'Sênior'), ('especialista', 'Especialista')], max_length=30, verbose_name='Senioridade'),
        ),
    ]
